### ISSUE TITLE
Eliminating Redundancy

### ISSUE THREAD

**Issue by robotsorcerer** [robustedu/Hexapod-Control#1]
Hi Xinmin, 

- What's the purpose of these [lines](https://github.com/robustedu/Hexapod-Control/blame/master/matlab/hexapod_con.m#L23-#L30) in your code? Am I correct in saying they are redundant?

- I am assuming that the variables with suffix `in_MOVING` refer to coordinates in the end effector frame. Wrong?

- Likewise, `in_COUCH` refers to coordinates in couch? Where in the couch is the frame assigned?\

- ~~What's the point of loading `xyz_psi.mat`, assigning `t1` and `t2` to  `target.xyz` and `target.psi` respectively  if `target.xyz` and `target.psi` are updated in the for loop, [here](https://github.com/robustedu/Hexapod-Control/blame/master/matlab/hexapod_con.m#L54-#L55)?~~

**Comment by robustedu** [comment]
1. As indicated in the code, the purpose is  %% Generate
target.xyz/psi_in_MOVING based on a given reasonable target.xyz/psi
If you want to simulation in computer, you need these data.
If you use the code for control, what you first obtained is target.xyz/psi
(in LINAC frame). And then you still need to compute
target.xyz/psi_in_MOVING.
So it is NOT redundant.

2. Right.

3. in_COUCH is the coordinates in couch frame. The couch position in LINAC
frame is given in the structure variable couch. It is couch.xyz/psi. If we
do not move the couch, the couch is in the normal position, i.e.,
couch.xyz/psi_normal.

**Comment by lakehanne** [comment]
Back on point 1:

You do not use `xyz_in_MOVING0` or `psi_in_MOVING0` as stated on [line 24] (https://github.com/robustedu/Hexapod-Control/blob/master/matlab/hexapod_con.m#L24) anywhere else in your code.

**Comment by robustedu** [comment]
Even if it is not used anywhere else, xyz/psi_in_MOVING0 is still a very
important variable. It indicates the target position in moving platform
frame when the patient is set up.

Indeed, it IS used in the code. Check one more time, and see if you can
find it :-)

**Comment by lakehanne** [comment]
I can reason with you when you say it is the initial pose info for the patient. But you do not use it elsewhere in this code as far as I can tell. 

If you did and it is relevant, please point it out.

**Comment by lakehanne** [comment]
Okay, I found it in your visualizations function. Never mind.

**Comment by lakehanne** [comment]
BTW, is there a major difference between your old lbfgs implementation and your current one?

I do not want to rewrite my LBFGS class if they are not significantly different

**Comment by robustedu** [comment]
The same.

**Comment by lakehanne** [comment]
Okay, this is a cleaner code compared to the first code you sent to me.

I just finished all the translations today. I will plot the charts tomorrow to see that the python results are exactly as what you have in matlab

**Comment by robustedu** [comment]
Nice. Thanks!

**Comment by lakehanne** [comment]
Sorry for the weekend disturbance. Your response can wait till Monday when you are at work.

What's the point of these arithmetic operations on the right hand side of these lines:

+    [Line X1](https://github.com/robustedu/Hexapod-Control/blob/master/matlab/plot_figs.m#L8)

+ [Lines X2](https://github.com/robustedu/Hexapod-Control/blob/master/matlab/plot_figs.m#L16)

**Comment by lakehanne** [comment]
Also, why the `180` factor in one, and `360` factor in the other?

Please reply directly in github as I would keep on adding more questions as I see them. It may not be updated in your inbox.

**Comment by robustedu** [comment]
- The point of these arithmetic operations is to clearly visualize three
   possible angle curves: sin(t), 180+cos(t), and 360+2*sin(t) all together in
   a single plot. The code is simple, you might remove these operations, and
   see what happens.
   - 1m=1000mm. :)
   - 1,2,3, are for xyz, 5,6,7 are for pitch/roll/yaw as indicated in the
   plots.

**Comment by lakehanne** [comment]
Makes sense. Thanks!

**Comment by lakehanne** [comment]
![image](https://user-images.githubusercontent.com/8429860/66780656-626c8280-ee9f-11e9-87e9-6a205db300f1.png)

**Comment by lakehanne** [comment]
![xinmin_mat](https://user-images.githubusercontent.com/8429860/66781204-aca23380-eea0-11e9-80f7-872874f07bdd.png)
